name: ci

on: [push, pull_request]

env:
  IDRIS2_VERSION: 0.4.0
  SCHEME: scheme

jobs:

  build-stable-idris2:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Cache Stable Version
        id: previous-version-cache
        uses: actions/cache@v2
        with:
          path: Idris2-${{ env.IDRIS2_VERSION }}
          key: ${{ runner.os }}-idris2-bootstrapped-${{ env.IDRIS2_VERSION }}
      - name : Bootstrap stable version
        if: steps.previous-version-cache.outputs.cache-hit != 'true'
        run: |
          wget https://www.idris-lang.org/idris2-src/idris2-$IDRIS2_VERSION.tgz
          tar zxvf idris2-$IDRIS2_VERSION.tgz
          cd Idris2-$IDRIS2_VERSION
          make bootstrap
          cd ..
      - name: Install stable version
        run: |
          cd Idris2-$IDRIS2_VERSION
          make install
          cd ..
      - name: Artifact Idris2
        uses: actions/upload-artifact@v2
        with:
          name: installed-idris2-${{ env.IDRIS2_VERSION }}-chez
          path: ~/.idris2/

  build-replica:
    needs: build-stable-idris2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Idris2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: installed-idris2-${{ env.IDRIS2_VERSION }}-chez
          path: ~/.idris2/
      - name: Install dhall
        uses: dhall-lang/setup-dhall@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          ls "$HOME/.idris2/bin"
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
      - name: Make replica
        run: make test
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: build
