name: ci

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    steps:
      - uses: actions/checkout@v2
      - name: Make replica
        run: make build
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: snazzybucket/idris2
    steps:
      - name: Install dhall
        uses: dhall-lang/setup-dhall@v4
      - uses: actions/checkout@v2
      - name: Restore artifact
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: build
      - run: chmod -R 500 build/exec
      - name: Test
        run: make test
