name: ci

on: [push, pull_request]

env:
  IDRIS2_VERSION: 0.3.0
  SCHEME: scheme

jobs:

  build-previous-idris2:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Cache Chez Previous Version
        id: previous-version-cache
        uses: actions/cache@v2
        with:
          path: Idris2-${{ env.IDRIS2_VERSION }}
          key: ${{ runner.os }}-idris2-bootstrapped-${{ env.IDRIS2_VERSION }}
      - name : Build previous version
        if: steps.previous-version-cache.outputs.cache-hit != 'true'
        run: |
          wget https://www.idris-lang.org/idris2-src/idris2-$IDRIS2_VERSION.tgz
          tar zxvf idris2-$IDRIS2_VERSION.tgz
          cd Idris2-$IDRIS2_VERSION
          make bootstrap-build
          cd ..
      - name: Install previous version
        run: |
          cd Idris2-$IDRIS2_VERSION
          make install
          cd ..
      - name: Artifact Idris2
        uses: actions/upload-artifact@v2
        with:
          name: installed-idris2-${{ env.IDRIS2_VERSION }}-chez
          path: ~/.idris2/

  build-idris2-nightly:
    needs: build-previous-idris2
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: idris-lang/idris2
          ref: master
      - name: Cache Idris2
        id: last-idris2
        uses: actions/cache@v2
        with:
          path: ~/.idris2
          key: ${{ runner.os }}-idris2-bootstrapped-${{ hashfiles('**/*.idr') }}
      - name: Download Idris2 Artifact
        if: steps.last-idris2.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v2
        with:
          name: installed-idris2-${{ env.IDRIS2_VERSION }}-chez
          path: ~/.idris2/
      - name: Install build dependencies
        if: steps.last-idris2.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
      - name: Build from previous version
        if: steps.last-idris2.outputs.cache-hit != 'true'
        run: make all && make install && make clean
      - name: Build self-hosted from previous version
        if: steps.last-idris2.outputs.cache-hit != 'true'
        run: make all && make install
      - name: Artifact Idris2
        uses: actions/upload-artifact@v2
        with:
          name: idris2-nightly
          path: ~/.idris2/

  build-replica:
    needs: build-idris2-nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Download Idris2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: idris2-nightly
          path: ~/.idris2/
      - name: Install dhall
        uses: dhall-lang/setup-dhall@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          ls "$HOME/.idris2/bin"
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
      - name: Make replica
        run: make build && make test
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: build
