name: docker

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Publish replica on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: |
          nix build .#docker.x86_64-linux
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push docker image to DockerHub
        run: |
          docker load < result
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/replica:latest
