name: docker

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Publish replica on Dcoker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push (latest)
        if: ${{ github.event_name != 'release'}}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/replica:latest
      - name: Build and push (release)
        if: ${{ github.event_name == 'release'}}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/replica:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/replica:${{ github.ref }}
